### ISSUE TITLE
imgui IM_ASSERT(g.FrameScopeActive) failure

### ISSUE THREAD

**Issue by astroesteban** [eliasdaler/imgui-sfml#113] opened 2020-01-02 20:43 UTC
Compiler: Visual Studio Community 2019 (MSVC 16)
Operating System: Windows 10 64-bit

**My Issue/Question:**

When running my application in x64-Debug I get:
`Assertion failed: g.FrameScopeActive, file C:\vcpkg\buildtrees\imgui\src\v1.73-a85d24b4b8\imgui.cpp, line 5400`
only when I add `ImGui::Begin` and `ImGui::End` calls to my source file.

I am attempting to start a new C++ project using vcpkg, CMake, and Visual Studio on windows. I installed the following packages through vcpkg:

-  imgui-sfml:x64-windows    v2.1
- imgui:x64-windows   v1.73-1
- sfml:x64-windows   v2.5.1-4

In my _CMakeLists.txt_ I include the following:
```
...
find_package(SFML CONFIG COMPONENTS REQUIRED windows graphics system)
find_package(imgui CONFIG REQUIRED)
find_package(ImGui-SFML CONFIG REQUIRED)
...
add_executable(main app/main.cpp)
target_link_libraries(main
                                PRIVATE imgui::imgui
                                              ImGui-SFML::ImGui-SFML
                                             sfml-system
                                             sfml-window
                                             sfml-graphics)
```

My _main.cpp_ file consists of the following:
```c++
#include <imgui.h>
#include <imgui-SFML.h>

#include <SFML/Graphics/RenderWindow.hpp>
#include <SFML/System/Clock.hpp>
#include <SFML/Window/Event.hpp>

int main()
{
	// Setup ImGui context
	ImGui::CreateContext();
	sf::RenderWindow window(sf::VideoMode(640, 480), "Test GUI");
	ImGui::SFML::Init(window);

	sf::Clock deltaClock;

	while (window.isOpen()) {
		sf::Event event{};
		while (window.pollEvent(event)) {
			ImGui::SFML::ProcessEvent(event);

			if (event.type == sf::Event::Closed) { window.close(); }
		}

		ImGui::SFML::Update(window, deltaClock.restart());

		ImGui::Begin("Test Begin");
                ImGui::Button("Test Button");
		ImGui::End();

		window.clear();
		ImGui::SFML::Render(window);
		window.display();
	} //end while

	ImGui::SFML::Shutdown();
}
```

When running my application in Visual Studio using the x64-Debug configuration I immediately get the following assertion failure for `IM_ASSERT(g.FrameScopeActive)`. This only happens when I add the lines
```
ImGui::Begin("Test Begin");
ImGui::Button("Test Button");
ImGui::End();
```

Without them I get a running black window (first image below).

I have been unable to find a solution to this problem. I am unsure if this is an issue with ImGui-SFML or ImGui itself. Any help with this would be greatly appreciated. Thank you!

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/12473592/71820810-f2ad0480-3055-11ea-97df-1674c7a679f9.png)
![error_2](https://user-images.githubusercontent.com/12473592/71820670-71557200-3055-11ea-8eca-6f7b85347805.png)

**Comment by eliasdaler** [comment] 2020-01-06 17:38
Did you try to run minimal example from README.md? Does it work?

This line looks suspicious - you don't need to do it:

```cpp
ImGui::CreateContext();
```

**Comment by DomRe** [comment] 2020-01-08 01:07
Running the example also triggers this for me:   
 IM_ASSERT(g.WithinFrameScope);                  // Forgot to call ImGui::NewFrame()

**Comment by esduran** [comment] 2020-01-08 13:05
I ran the minimal example from the README and still get the same result. I don't think ImGui::NewFrame() is actually being called.

**Comment by eliasdaler** [comment] 2020-01-09 09:38
Can you please debug why it doesn't get called? At the moment I'm not able to reproduce this on my machine.

See the call to `ImGui::NewFrame` here: https://github.com/eliasdaler/imgui-sfml/blob/master/imgui-SFML.cpp#L455

You need to make sure that this `ImGui::SFML::Update` gets called **before** any `ImGui::Begin` calls

**Comment by chenzdshao** [comment] 2020-01-10 07:07
I encountered the same issue!

**Comment by eliasdaler** [comment] 2020-01-10 12:41
@chenzdshao can you please debug it a bit as I've described in my previous comment?

**Comment by chenzdshao** [comment] 2020-01-12 08:24
@eliasdaler When I build and link ImGui-SFML.lib with vcpkg or cmake, here comes the error. When I compile and link imgui-SFML.cpp manually, the error disappears!

**Comment by eliasdaler** [comment] 2020-01-12 12:29
This means there are some problems with imgui-sfml's vcpkg package, and so the issue should probably be created in vcpkg repo...

**Comment by esduran** [comment] 2020-01-13 14:01
I encounter the same thing as @chenzdshao. I will open a new issue in the vcpkg repo.

**Comment by JackBoosY** [comment] 2020-01-15 08:15
After debugging, I found that there are multiple variable `GimGuis`, the first variable is initialized, and the second variable is used subsequently.
I don't know why .I can reproduce it in Visual Studio 2019, but not in Visual Studio 2017.

Anyone can help me?

**Comment by eliasdaler** [comment] 2020-01-15 13:17
Might be something to do with linking and having multiple copies of one static object.
Can you try to link imgui-sfml statically?

**Comment by JackBoosY** [comment] 2020-01-17 08:34
@esduran Why is `GimGui` not set as a static variable to avoid this situation?

**Comment by eliasdaler** [comment] 2020-01-17 10:31
This is not something that I can control - it's an ImGui thing... Both static and dynamic linking work fine for me if I compile sources myself. vcpkg does something wrong, I can't tell what...

**Comment by esduran** [comment] 2020-01-17 13:27
The issue is also [opened](https://github.com/microsoft/vcpkg/issues/9660) in vcpkg. 
I'll go ahead and compile the sources myself as well.

**Comment by Eric-Ackles** [comment] 2020-01-24 07:41
The vcpkg port of *imgui* enforces to build it as a static library. Its *portfile.cmake* has a `vcpkg_check_linkage(ONLY_STATIC_LIBRARY)` command.

But *imgui-sfml* is built as dll by vcpkg (default triplet). Then your executable and the dll will be linked to the static library twice.

https://stackoverflow.com/questions/31209693/static-library-linked-two-times

**Comment by eliasdaler** [comment] 2020-01-24 09:21
Then maybe ImGui-SFML should only be build as static lib as well?

**Comment by eliasdaler** [comment] 2020-11-18 14:00
Looks like it's been fixed in vcpkg package.

**Closed by eliasdaler** 2020-11-18 14:00 UTC
