### ISSUE TITLE
[Linux] Font rendering problem

### ISSUE THREAD

**Issue by lorow** [eliasdaler/imgui-sfml#33] opened 2017-05-22 11:23 UTC
Hi @eliasdaler! 
Today I treid to setup Imgui and SFML on my linux machine (newest Manjaro Deepin) but an unexpected problem occured. The imgui font isn't rendering properly, I can see only some glitches, like on the screenshoot. I asked @ocornut about it but he only said that I should ask you. 

Here's the screenshoot. 
![4p5gopv](https://cloud.githubusercontent.com/assets/14099558/26305723/d685beb8-3ef0-11e7-90c4-7534e2d56d18.png)

My main.cpp looks exactly like this one from the readme so the problem isn't probably there. 

my cmakelists.txt file looks like this :

```
cmake_minimum_required(VERSION 3.7)
project(untitled)

set(CMAKE_CXX_STANDARD 14)

set(SOURCE_FILES main.cpp)

#detect and add all imgui files
file(GLOB imgui_src "imgui-master/*.*" )
file(GLOB imgui_sfml_src "imgui-master/imgui-sfml-master/*.*" )
file(GLOB fonts "imgui-master/extra_fonts/*.*")
#prepare executable
add_executable(untitled ${SOURCE_FILES} ${imgui_src} ${imgui_sfml_src} ${fonts})


# Detect and add SFML
set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake_modules" ${CMAKE_MODULE_PATH})
#Find any version 2.X of SFML
#See the FindSFML.cmake file for additional details and instructions
find_package(SFML REQUIRED network audio graphics window system)
if(SFML_FOUND)
    include_directories(${SFML_INCLUDE_DIR})
    target_link_libraries(untitled ${SFML_LIBRARIES} ${SFML_DEPENDENCIES})
endif()

# OpenGL
find_package(OpenGL REQUIRED)
include_directories(${OPENGL_INCLUDE_DIR})
if (OPENGL_FOUND)
    target_link_libraries(untitled ${OPENGL_LIBRARIES})
    # or: target_link_libraries(${EXECUTABLE_NAME} ${OPENGL_gl_LIBRARY})
    target_link_libraries(untitled m)  # if you use maths.h
endif()
```

I also tried solutions mentionek in #23 , they didn't help too. 

Thanks a lot for any help!

**Comment by eliasdaler** [comment] 2017-05-22 12:21
Hi. What SFML version are you using? The same problem was once fixed by one user when he updated SFML to latest version. 

If you're using the latest version and the problem still exists, can you please show me minimal reproducing example? It will help a lot for tracking the bug.

And the last thing: try calling target.resetGLStates(); just before calling ImGui::Render(). This seems to solve 99% of errors and I'll add this call to ImGui-SFML soon.

**Comment by lorow** [comment] 2017-05-22 13:23
It looks like adding this fixed the problem. 
![image](https://cloud.githubusercontent.com/assets/14099558/26310781/611d7a1e-3f02-11e7-8f2f-f3ad23deeb7b.png)
And my version of SFML is 2.4.2. Anyway, thanks a lot for help!

**Comment by eliasdaler** [comment] 2017-05-22 15:13
Haha, that call is really a solution to most problems. I'll create ImGui::SFML:: Render (sf:: RenderTarget&) function which will call resetGLstates soon.

**Closed by eliasdaler** 2017-05-22 15:13 UTC

**Comment by MonkahTV** [comment] 2017-05-24 16:50
Still having this issue. Did you mean resetting the window, or something else?

`		window.clear();
		window.draw(shape);
		window.resetGLStates();
		ImGui::Render();
		window.display();`

**Comment by eliasdaler** [comment] 2017-05-24 17:46
Yeah. Does new example which uses ImGui::SFML::Render not work as well?

**Comment by MonkahTV** [comment] 2017-05-24 17:53
Same problem, unfortunately. White boxes.

Are there any objects/details you'd like me to provide?

**Comment by eliasdaler** [comment] 2017-05-24 19:40
What system are you using? Are you sure you're using the latest SFML version? Can you try and build OpenGL examples from ImGui and see if they run correctly?

**Comment by MonkahTV** [comment] 2017-05-25 14:48
1. Windows, x86 Release
2. It was downloaded within the last ~two weeks.
3. They're running just fine-- certainly no font issues, although the issue in this example only happens after pushing a font, which the examples don't do AFAIK.

**Comment by MonkahTV** [comment] 2017-05-25 14:51
Windows, x86 Release. It was downloaded within the last ~two weeks, so almost definitely.

OpenGL examples don't really interact with the font much, and seem to be fine.

**Comment by eliasdaler** [comment] 2017-05-25 20:19
But they display some text, so if it works, then there's nothing wrong with your graphics card drivers.

How does this line cause troubles? Did you try it and something worked? Because honestly it works fine for me and for a lot of people who used the binding, so it's pretty hard to track the problem...

**Comment by MonkahTV** [comment] 2017-05-26 14:15
I can provide [code](https://gist.github.com/MonkahTV/86bd03bbe143a3a21747ea553d2d278d), but other than that, I'm not really sure what other diagnostics I have.

The program crashes without the GetTexData() function, I should probably add. The 'pixels' character has a hex value of 255, which could explain why the boxes are all white squares, if my understanding of what 'pixels' does is correct.

Any ideas?

**Comment by eliasdaler** [comment] 2017-05-26 22:09
Are you calling ImGui::SFML::Init? It's **very** important. I understand that using other fonts is not supported right now with ImGui-SFML, but does default example work?

**Comment by MonkahTV** [comment] 2017-05-30 12:24
Sorry for the late reply.

The default font works, yeah-- just using your own fonts seems to result in white-cubes of death/doom/disaster/any other negative adjective that begins with 'd'.

And yeah, we use the initialization function. Here, [fullcode](https://pastebin.com/DVB3haUZ), if you want to give it a peek of your own. The odd thing is that I specifically remember font-loading to work perfectly well back on the Linux platform-- although I no longer have access to the old code that I used there, so I'm unable to provide whether this is a platform-specific issue or not.

Any more ideas, by chance?

**Comment by eliasdaler** [comment] 2017-05-30 22:24
Thanks for the minimal example, I see what I can do soon. :)

**Comment by mikeagam-dev** [comment] 2017-06-01 09:42
Thanks, Elias! Let me know what you find.

**Comment by MonkahTV** [comment] 2017-06-01 09:45
Thanks, Elias! Do let me know what you find; I've been squirming with this one for quite some time now.

Cheers!

**Comment by eliasdaler** [comment] 2017-06-01 12:21
Okay. I hope it's not urgent. I'm quite busy with the studying, but I might have some time to work on the problem today.

**Comment by eliasdaler** [comment] 2017-06-01 22:59
@MonkahTV [check it out](https://github.com/eliasdaler/imgui-sfml#fonts-how-to), looks good to me.

**Comment by MonkahTV** [comment] 2017-06-02 14:33
Solid. Cheers, Elias!

**Comment by eliasdaler** [comment] 2017-06-02 21:08
Glad it worked for you. :)
