### ISSUE TITLE
SIGSEV on calling  ImGui::GetWindowSize();  

### ISSUE THREAD

**Issue by traw** [eliasdaler/imgui-sfml#31] opened 2017-04-23 11:49 UTC
Crash on calling  `ImGui::GetWindowSize()` before calling `ImGui::SFML::Update(window, deltaClock.restart())`
 Stack Trace:   
`Program received signal SIGSEGV, Segmentation fault.
0x000000000042b723 in ImGui::GetWindowSize () at /proj/imgui-sfml-addons/imgui.cpp:4939
4939	    return window->Size;
(gdb) bt
#0  0x000000000042b723 in ImGui::GetWindowSize () at /proj/imgui-sfml-addons/imgui.cpp:4939
#1  0x0000000000406a50 in main () at /proj/testMain.cpp:52
`

**Comment by eliasdaler** [comment] 2017-04-23 21:39
Can you post a minimal reproducing example?

Btw, if you're trying to get SFML's window size, you should use ImGui::GetIO().DisplaySize, because AFAIK, GetWindowSize() returns the size of a window which was created with ImGui. If you're creating ImGui widgets, you should call ImGui::SFML::Update first.

**Comment by eliasdaler** [comment] 2017-05-22 21:17
Closing for now, feel free to comment if the problem is still not solved.

**Closed by eliasdaler** 2017-05-22 21:17 UTC
